// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class UpdateOperator extends ethereum.Event {
  get params(): UpdateOperator__Params {
    return new UpdateOperator__Params(this);
  }
}

export class UpdateOperator__Params {
  _event: UpdateOperator;

  constructor(event: UpdateOperator) {
    this._event = event;
  }

  get _tokenId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get _operator(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class Rentable extends ethereum.SmartContract {
  static bind(address: Address): Rentable {
    return new Rentable("Rentable", address);
  }
}
